maxTotal: 500
maxConnectionPerHost: 500
connectionTimeout: 60000
connectionRequestTimeout: 60000
soTimeout: 60000
idleTimeout: 30000
#url: "http://10.79.94.22:8180"
url: "https://36.37.242.116:8301"
sslDisable: true
apiKey: "epa 2478e27af578e11a6af86a8320562124240f5c972e8039cd9c564e53d643bb31"
merchantCode: "ePayTest"
#privateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCY6EbOULc7ksASsPnO3mKj21tBIeuw2BBI+56OesX45qbEbs4pRzpqzPcj65jgHmSEfYwa5JNGcmGi3JD4ixJFIQzyUvmk+7XZUint04rMyYzrzKHeUcTv/jZ5P0Z/vqXSgFzaciDdnG2K159IjNt/adedcDVPQJ7q6D7qm94LaghTQh9rA1PXF7L1zVne5G51llAuY2FKUt0HXp4W5ZhcqgpiLlalKPYPNfwACkbkREmse9ibjvpIfEsg5USw1wFuqRG0FarZNO6y8iTVj1wZSob33/BG2FhGVUxyUGLN0mS1lfCFU3aitrgdkeoLSRfq8zi/mEk4n6kk4u/YHM1nAgMBAAECggEAKmXdnD+NTxt13rjry4ymVUDxoLHDJJoEifgbEu7ADjAGddkzmQaDEDIdJPyiuyIyRPp66soOfC4jHIGEQSZuvnRXnqmbRz/0QHoj3ioWBoqsZIWtLHQH43Pdruj4p1s5p5CoLnoO2uQRC7qWFAvaoQ28F4+ReJQ2fHRBXdQyUX97PzQszZyAQWc/9UbUEyeZim9xl+SRKssP0u5d5Duh/2CTieZbOXh+4lLe1/mv2aXtSQCFiW8wgWXYJE03q8kSediKwuxfG//Dj5+oR6dz96wyLLao94HemRFNYZq8CoJs5z1eyuj2QYxQGgEhZJYTyl0hDK7+JwSNPldLtOae4QKBgQDRvmocabHoCUYKgjJKCtSAfSF+y/U5iwDsH1FZYhp8ZxkBuALWVD2FhtuZYbGvzDYuYSpLa/VITRR5yBTUXuhLNSPUOIDLS3Ba9V38SdxsWKSgBkTRdE6O9ShkEQfBMQ0v17JTfATCn7lUTRCqV3ayAkfJNqVh+TpZWCI5u/SsywKBgQC6oQYMyPMCAeTMSHVYJ4WUWDz5ZxOyqQCIvicQtunJ7U2Y/+iY8ZQl1B6jJ/JColBjxqTqFIq8LFdJD7VkE+/AKFjwr0RgTy2tRqJNvyaSrIdVi/6OI+y1RXS4VBiY+SZ5wobx1v1t7se4ltdN71Xbuzz/QmXDCtbMPLam8u6KVQKBgQCb1H/buj9eaL1sA00/q4o0KEOhhAEejoLR63ayFOwery5qE3+wI4hN02MGMwoj1XIPxUr6HCxxWiszS48GNbkaX1HOU2iFIfhI6/G3Bl1I9hbheabZgzL2jXhD2E9Nnpbwi63GzuZufuLfmh4eoLrkCEOzX/FBuDw8svlCsb1YPwKBgFgfKj0lMWFURZWT7RyH5NIL7BaTbkCg/iiTKN0CkVeQXmCNDWYSQ7Ks+x5tAT4naDAEnuAMfQmnIjvUWAD+TOl946kaCP40xMuZm498X5lIL8rcBIFXQzDAsAFNbCPnGRzLFm7g5d9frRxi1RzukqrjOUUKNASpfI0JafFgqfPVAoGAI1Oz2PsG4phr8USI7cB1P0mVOc+69tn6QA/oDT8dBqO9bVuBRuQsVgoPPKTbusK1Na0NDmMAfgwRynxPCwwSevGiWlCGFZGj+eM9a52g6BbbHT2LGsQqWsLINFBOAwUAPoyOyB76EC1iQ2FM/mvQbBwnsNaG6SZX73dchlkn7iU="
#publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn0dF9WwFY8Te4AEoGdTC34c9vStRegi9D9H4jXXNoOAMyRPH+e9I+ZTJfERpIs45j+Y+KezmI0bFJ/mk06ZK9Si9V81aeBsgtgy5Ul4reQYkH9KL0G7hboX1eePkmc95qCQFwGD3PEITKD6ei43YxYfOf8BltHFZ0Z+opkTTZHW5aOMAFUIRoaXTpaVD+I7rx6gDJX+pZsPowLpfFjGAY2YRe2FJN1YXtyJFEDhRJDeqY4QakelyKGDK8gi5CFLxDtkUxpF3QWUk98WLJH/mkGJUmKAORksVR7ReaHbEWQkJUuDUxh0YUr9X7aXGZnbHAuDTbUqCP4L/wFBIhWWaOwIDAQAB"
#privateKey: "D:\\camid\\sources\\camid-process-app\\etc\\epayment\\ePayTest.pri"
#publicKey: "D:\\camid\\sources\\camid-process-app\\etc\\epayment\\ePayTest.pub"
privateKey: "../etc/epayment/ePayTest.pri"
publicKey: "../etc/epayment/ePayTest.pub"
secretCode: "7260902e74aea6971a8ba830e1b2fec6"
apis:
  initTransfer: "transfer/init"
  confirmTransfer: "transfer/confirm"
  checkTransaction: "trans/check"
configurations:
  isOfflineCrawMode: false
